config/routes.rb
Rails.application.routes.draw do
  resources :user_events
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avro/user.rb
module Avro
  class User
    include Avromatic::Model.build(schema_name: 'user', namespace: 'users')
    AvroSchemaRegistry::Client.new()
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_events
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user

  enum event_type: %i(user_viewed user_created user_updated user_deleted)
end

app/models/user_event_datum.rb
class UserEventDatum < ApplicationRecord
  belongs_to :user

  enum event_type: %i(user_viewed user_created user_updated user_deleted)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def show
  #   @comment = Comment.find(params[:id])

  #   event = {
  #     name: "comment_viewed",
  #     data: {
  #       comment_id: @comment.id,
  #       user_id: current_user.id
  #     }
  #   }

  #   # By delivering messages asynchronously you free up your server processes faster.
  #   DeliveryBoy.deliver_async(event.to_json, topic: "activity")
  # end

  # def create
  #    @comment = Comment.create!(params)

  #    event = {
  #      name: "comment_created",
  #      data: {
  #        comment_id: @comment.id
  #        user_id: current_user.id
  #      }
  #    }

  #    # This will queue the two messages in the internal buffer.
  #    DeliveryBoy.produce(comment.to_json, topic: "comments")
  #    DeliveryBoy.produce(event.to_json, topic: "activity")

  #    # This will deliver all messages in the buffer to Kafka.
  #    # This call is blocking.
  #    DeliveryBoy.deliver_messages
  #  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user_event, only: %i[ show ]

  # GET /user_events or /user_events.json
  def index
    @user_events = UserEvent.all
  end

  # GET /user_events/1 or /user_events/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_event
      @user_event = UserEvent.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    save_event(@user.id, 0, @user.attributes)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        save_event(@user.id, 1, @user.attributes)
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        save_event(@user.id, 2, @user.attributes)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    respond_to do |format|
      if @user.update(deleted: true)
        save_event(@user.id, 3, @user.attributes)
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :bio)
    end

    def save_event(user_id, type, value)
      user_event = UserEvent.new(user_id: user_id, event_type: type, value: value)
      DeliveryBoy.deliver_async(value, topic: user_event.event_type)
      user_event.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_event_data_helper.rb
module UserEventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventDrivenApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_event_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Event Data</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_event_data.each do |user_event_datum| %>
      <tr>
        <td><%= user_event_datum.user_id %></td>
        <td><%= user_event_datum.event_type %></td>
        <td><%= user_event_datum.value %></td>
        <td><%= link_to 'Show', user_event_datum %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Event Data</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_events.each do |user_event| %>
      <tr>
        <td><%= user_event.user_id %></td>
        <td><%= user_event.event_type %></td>
        <td><%= user_event.value %></td>
        <td><%= link_to 'Show', user_event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_event.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user_event.event_type %>
</p>

<p>
  <strong>Value:</strong>
  <%= @user_event.value %>
</p>

<%= link_to 'Back', user_events_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>